# ===============================
# [ Linden Honey Properties ]
# ===============================
linden-honey:
  app:
    name: Linden Honey
    port: 8080
  db:
    uri: mongodb://linden-honey:linden-honey@localhost:27017/linden-honey
    migration:
      enabled: true
      scan-package: com.github.lindenhoney.migration


# ===============================
# [ Server Properties ]
# ===============================
server:
  port: ${linden-honey.app.port}


# ===============================
# [ Spring Properties ]
# ===============================
spring:
  profiles:
    active: dev
  application:
    name: ${linden-honey.app.name}
  data:
    mongodb:
      uri: ${linden-honey.db.uri}


# ===============================
# [ Logging Properties ]
# ===============================
logging:
  level:
    com:
      github:
        lindenhoney: DEBUG
    org:
      springframework: INFO
